### YamlMime:UniversalReference
ms.openlocfilehash: 388e022c41872f41fc3ff1a4f5bee98d77b1c567
ms.sourcegitcommit: 8f2555cd23e454ff79e27bd3ed0a6f65b08c1c9e
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/10/2018
ms.locfileid: "48523552"
items:
- uid: '@azure/event-hubs.ErrorNameConditionMapper'
  name: ErrorNameConditionMapper
  fullName: ErrorNameConditionMapper
  children:
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  - '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  - '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  - '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  - '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="4593f-101">Сопоставляет имена ошибок условий ошибки amqp.</span><span class="sxs-lookup"><span data-stu-id="4593f-101">Maps the Error names to the amqp error conditions.</span></span>
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  name: ArgumentError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-102">Ошибка возникает в том случае, если получен неправильный аргумент.</span><span class="sxs-lookup"><span data-stu-id="4593f-102">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  name: UnauthorizedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-103">Ошибка возникает в том случае, когда указаны неверные параметры подключения и сервера отказывает в соединении.</span><span class="sxs-lookup"><span data-stu-id="4593f-103">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  name: ConnectionForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-104">Когда оператор intervened, чтобы закрыть соединение, для какой-либо причине, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-104">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  name: ConnectionRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-105">Ошибка возникает в том случае, если контейнер больше не доступны в текущем соединении.</span><span class="sxs-lookup"><span data-stu-id="4593f-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  name: DecodeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-106">Ошибка возникает в том случае, когда не удалось расшифровать данные.</span><span class="sxs-lookup"><span data-stu-id="4593f-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  name: DetachForcedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-107">Когда оператор intervened для отсоединения для какой-либо причине, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-107">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  name: ErrantLinkError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-108">Ошибка возникает в том случае, если ввод получен ссылку, которая была отсоединена с ошибкой.</span><span class="sxs-lookup"><span data-stu-id="4593f-108">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  name: FrameSizeTooSmallError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-109">Ошибка возникает в том случае, когда одноранговый узел не удается отправить кадр, поскольку наименьшее кодировку перформатива значениями действителен в настоящее время может быть слишком велик для обработки в рамке согласованный максимальный размер кадра.</span><span class="sxs-lookup"><span data-stu-id="4593f-109">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  name: FramingError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-110">Ошибка создается в том случае, если допустимые рамки заголовка не может быть сформированы из входящего потока.</span><span class="sxs-lookup"><span data-stu-id="4593f-110">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  name: HanldeInUseError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-111">При получении операции присоединения, используя дескриптор, который уже используется для присоединенных ссылок, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-111">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  name: IllegalStateError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-112">Одноранговый узел об отправке кадра, который не поддерживается в текущем состоянии, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-112">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  name: InternalServerError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-113">Ошибка возникает в том случае, когда произошла внутренняя ошибка сервера.</span><span class="sxs-lookup"><span data-stu-id="4593f-113">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="4593f-114">Нашли ошибку?</span><span class="sxs-lookup"><span data-stu-id="4593f-114">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  name: InvalidFieldError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-115">Ошибка возникает в том случае, когда было передано недопустимое поле в теле кадра, а не удается выполнить операцию.</span><span class="sxs-lookup"><span data-stu-id="4593f-115">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  name: InvalidOperationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-116">Ошибка возникает в том случае, когда операция выполняется, но не допускается.</span><span class="sxs-lookup"><span data-stu-id="4593f-116">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  name: LinkRedirectError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-117">Ошибка возникает в том случае, если указанный адрес не может быть разрешено собой конечную точку, в текущем контейнере.</span><span class="sxs-lookup"><span data-stu-id="4593f-117">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  name: MessageLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-118">Ошибка возникает в том случае, когда блокировка сообщения теряется.</span><span class="sxs-lookup"><span data-stu-id="4593f-118">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  name: MessageTooLargeError
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="4593f-119">Ошибка возникает, когда это сообщение отправлено слишком велик: максимальный размер составляет 256 КБ.</span><span class="sxs-lookup"><span data-stu-id="4593f-119">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  name: MessagingEntityDisabledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-120">При попытке доступа или подключения к ним с отключенной сущностью обмена сообщениями, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-120">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  name: ArgumentOutOfRangeError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-121">Если аргумент имеет значение, которое находится за пределами допустимой диапазона, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-121">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  name: OperationCancelledError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-122">Когда сервер отменяет операцию из-за Внутренняя ошибка, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-122">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  name: PreconditionFailedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-123">Ошибка возникает в том случае, когда условие, которое следует будут соблюдены для выполнения операции.</span><span class="sxs-lookup"><span data-stu-id="4593f-123">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  name: QuotaExceededError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="4593f-124">Возникает ошибка была превышена квота концентратора событий Azure и служебной шины.</span><span class="sxs-lookup"><span data-stu-id="4593f-124">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="4593f-125">Периодический сброс квоты, эта операция будет ожидать до тех пор.</span><span class="sxs-lookup"><span data-stu-id="4593f-125">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="4593f-126">Сущность обмена сообщениями достигла максимально допустимого размера.</span><span class="sxs-lookup"><span data-stu-id="4593f-126">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="4593f-127">Это может произойти, если уже было открыто максимальное число получателей (равное 5) на группу потребителей.</span><span class="sxs-lookup"><span data-stu-id="4593f-127">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  name: ReceiverDisconnectedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-128">Ошибка возникает в том случае, когда два или более экземпляров подключаются к одной секции со значениями разных эпохи.</span><span class="sxs-lookup"><span data-stu-id="4593f-128">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  name: ResourceDeletedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-129">При удалении объекта сервера, которыми он работает с, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-129">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  name: ResourceLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-130">Ошибка возникает при попытке выполнить клиент для работы с объектом сервера, к которому она не имеет доступа, так как другой клиент работает с ним.</span><span class="sxs-lookup"><span data-stu-id="4593f-130">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  name: SenderBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-131">Ошибка возникает в том случае, когда отправитель клиента не имеет достаточно кредитов ссылку для отправки сообщения.</span><span class="sxs-lookup"><span data-stu-id="4593f-131">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  name: ServerBusyError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-132">Ошибка возникает в том случае, когда сервер занят.</span><span class="sxs-lookup"><span data-stu-id="4593f-132">Error is thrown when the server is busy.</span></span> <span data-ttu-id="4593f-133">Вызывающие объекты должны через некоторое время и повторите операцию.</span><span class="sxs-lookup"><span data-stu-id="4593f-133">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  name: ServiceCommunicationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-134">Ошибка сообщения об обнаружении ошибок общие связи, относящиеся к операций обмена сообщениями.</span><span class="sxs-lookup"><span data-stu-id="4593f-134">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  name: ServiceUnavailableError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-135">Ошибка возникает в том случае, если служба недоступна.</span><span class="sxs-lookup"><span data-stu-id="4593f-135">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="4593f-136">Следует повторить операцию.</span><span class="sxs-lookup"><span data-stu-id="4593f-136">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  name: SessionCannotBeLockedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-137">Ошибка возникает в том случае, заблокированной сеансов служебной шины Azure.</span><span class="sxs-lookup"><span data-stu-id="4593f-137">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  name: SessionLockLostError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-138">Ошибка возникает в том случае, когда теряется блокировку сеанса служебной шины Azure.</span><span class="sxs-lookup"><span data-stu-id="4593f-138">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  name: SessionWindowViolationError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-139">Ошибка возникает при входящих окно однорангового узла для сеанса.</span><span class="sxs-lookup"><span data-stu-id="4593f-139">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  name: SystemError
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="4593f-140">При возникновении ошибки низкого уровня системы, node.js, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-140">Error is thrown when a low level system error is thrown by node.js.</span></span>

    <xref:https%3A%2F%2Fnodejs.org%2Fapi%2Ferrors.html%23errors_class_systemerror>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  name: TransferLimitExceededError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-141">Одноранговый узел об отправке дополнительные передачу сообщений, чем разрешено в настоящее время ссылку, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="4593f-141">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  name: UnattachedHandleError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-142">Ошибка возникает в том случае, если кадр (кроме присоединения) получен ссылается на дескриптор, который сейчас не используется, вложенные связи.</span><span class="sxs-lookup"><span data-stu-id="4593f-142">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  name: NotImplementedError
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="4593f-143">Ошибка возникает в том случае, когда функция не реализована, но присутствует заполнитель.</span><span class="sxs-lookup"><span data-stu-id="4593f-143">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
