### YamlMime:UniversalReference
ms.openlocfilehash: 388e022c41872f41fc3ff1a4f5bee98d77b1c567
ms.sourcegitcommit: 8f2555cd23e454ff79e27bd3ed0a6f65b08c1c9e
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 10/10/2018
ms.locfileid: "48523552"
items:
- uid: '@azure/event-hubs.ErrorNameConditionMapper'
  name: ErrorNameConditionMapper
  fullName: ErrorNameConditionMapper
  children:
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  - '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  - '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  - '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  - '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  - '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  - '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  - '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  - '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  - '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  - '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  langs:
  - typeScript
  type: enum
  summary: Сопоставляет имена ошибок условий ошибки amqp.
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentError'
  name: ArgumentError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если получен неправильный аргумент.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnauthorizedError'
  name: UnauthorizedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда указаны неверные параметры подключения и сервера отказывает в соединении.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionForcedError'
  name: ConnectionForcedError
  children: []
  langs:
  - typeScript
  summary: Когда оператор intervened, чтобы закрыть соединение, для какой-либо причине, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ConnectionRedirectError'
  name: ConnectionRedirectError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если контейнер больше не доступны в текущем соединении.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DecodeError'
  name: DecodeError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда не удалось расшифровать данные.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.DetachForcedError'
  name: DetachForcedError
  children: []
  langs:
  - typeScript
  summary: Когда оператор intervened для отсоединения для какой-либо причине, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ErrantLinkError'
  name: ErrantLinkError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если ввод получен ссылку, которая была отсоединена с ошибкой.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FrameSizeTooSmallError'
  name: FrameSizeTooSmallError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда одноранговый узел не удается отправить кадр, поскольку наименьшее кодировку перформатива значениями действителен в настоящее время может быть слишком велик для обработки в рамке согласованный максимальный размер кадра.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.FramingError'
  name: FramingError
  children: []
  langs:
  - typeScript
  summary: Ошибка создается в том случае, если допустимые рамки заголовка не может быть сформированы из входящего потока.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.HanldeInUseError'
  name: HanldeInUseError
  children: []
  langs:
  - typeScript
  summary: При получении операции присоединения, используя дескриптор, который уже используется для присоединенных ссылок, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.IllegalStateError'
  name: IllegalStateError
  children: []
  langs:
  - typeScript
  summary: Одноранговый узел об отправке кадра, который не поддерживается в текущем состоянии, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InternalServerError'
  name: InternalServerError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда произошла внутренняя ошибка сервера. Нашли ошибку?
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidFieldError'
  name: InvalidFieldError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда было передано недопустимое поле в теле кадра, а не удается выполнить операцию.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.InvalidOperationError'
  name: InvalidOperationError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда операция выполняется, но не допускается.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.LinkRedirectError'
  name: LinkRedirectError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если указанный адрес не может быть разрешено собой конечную точку, в текущем контейнере.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageLockLostError'
  name: MessageLockLostError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда блокировка сообщения теряется.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessageTooLargeError'
  name: MessageTooLargeError
  children: []
  langs:
  - typeScript
  summary: 'Ошибка возникает, когда это сообщение отправлено слишком велик: максимальный размер составляет 256 КБ.'
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.MessagingEntityDisabledError'
  name: MessagingEntityDisabledError
  children: []
  langs:
  - typeScript
  summary: При попытке доступа или подключения к ним с отключенной сущностью обмена сообщениями, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ArgumentOutOfRangeError'
  name: ArgumentOutOfRangeError
  children: []
  langs:
  - typeScript
  summary: Если аргумент имеет значение, которое находится за пределами допустимой диапазона, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.OperationCancelledError'
  name: OperationCancelledError
  children: []
  langs:
  - typeScript
  summary: Когда сервер отменяет операцию из-за Внутренняя ошибка, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.PreconditionFailedError'
  name: PreconditionFailedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда условие, которое следует будут соблюдены для выполнения операции.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.QuotaExceededError'
  name: QuotaExceededError
  children: []
  langs:
  - typeScript
  summary: >-
    Возникает ошибка была превышена квота концентратора событий Azure и служебной шины.

    Периодический сброс квоты, эта операция будет ожидать до тех пор.

    Сущность обмена сообщениями достигла максимально допустимого размера.

    Это может произойти, если уже было открыто максимальное число получателей (равное 5) на группу потребителей.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ReceiverDisconnectedError'
  name: ReceiverDisconnectedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда два или более экземпляров подключаются к одной секции со значениями разных эпохи.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceDeletedError'
  name: ResourceDeletedError
  children: []
  langs:
  - typeScript
  summary: При удалении объекта сервера, которыми он работает с, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ResourceLockedError'
  name: ResourceLockedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает при попытке выполнить клиент для работы с объектом сервера, к которому она не имеет доступа, так как другой клиент работает с ним.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SenderBusyError'
  name: SenderBusyError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда отправитель клиента не имеет достаточно кредитов ссылку для отправки сообщения.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServerBusyError'
  name: ServerBusyError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда сервер занят. Вызывающие объекты должны через некоторое время и повторите операцию.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceCommunicationError'
  name: ServiceCommunicationError
  children: []
  langs:
  - typeScript
  summary: Ошибка сообщения об обнаружении ошибок общие связи, относящиеся к операций обмена сообщениями.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.ServiceUnavailableError'
  name: ServiceUnavailableError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если служба недоступна. Следует повторить операцию.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionCannotBeLockedError'
  name: SessionCannotBeLockedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, заблокированной сеансов служебной шины Azure.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionLockLostError'
  name: SessionLockLostError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда теряется блокировку сеанса служебной шины Azure.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SessionWindowViolationError'
  name: SessionWindowViolationError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает при входящих окно однорангового узла для сеанса.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.SystemError'
  name: SystemError
  children: []
  langs:
  - typeScript
  summary: >-
    При возникновении ошибки низкого уровня системы, node.js, выдается ошибка.

    <xref:https%3A%2F%2Fnodejs.org%2Fapi%2Ferrors.html%23errors_class_systemerror>
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.TransferLimitExceededError'
  name: TransferLimitExceededError
  children: []
  langs:
  - typeScript
  summary: Одноранговый узел об отправке дополнительные передачу сообщений, чем разрешено в настоящее время ссылку, выдается ошибка.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.UnattachedHandleError'
  name: UnattachedHandleError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, если кадр (кроме присоединения) получен ссылается на дескриптор, который сейчас не используется, вложенные связи.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
- uid: '@azure/event-hubs.ErrorNameConditionMapper.NotImplementedError'
  name: NotImplementedError
  children: []
  langs:
  - typeScript
  summary: Ошибка возникает в том случае, когда функция не реализована, но присутствует заполнитель.
  type: field
  numericValue: 
  package: '@azure/event-hubs'
