### YamlMime:UniversalReference
ms.openlocfilehash: 22a643175009a3e2b6a48681140d1f1dbae34757
ms.sourcegitcommit: 87f95d58ec8de16e115bc344efeb084afc346b74
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 08/12/2018
ms.locfileid: "40074980"
items:
- uid: azure-event-hubs.ConditionErrorNameMapper
  name: ConditionErrorNameMapper
  fullName: ConditionErrorNameMapper
  children:
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:forced
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:timeout
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:redirect
  - azure-event-hubs.ConditionErrorNameMapper.amqp:decode-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:frame-size-too-small
  - azure-event-hubs.ConditionErrorNameMapper.amqp:illegal-state
  - azure-event-hubs.ConditionErrorNameMapper.amqp:internal-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:invalid-field
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:detach-forced
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:message-size-exceeded
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:redirect
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:stolen
  - azure-event-hubs.ConditionErrorNameMapper.amqp:link:transfer-limit-exceeded
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-allowed
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-found
  - azure-event-hubs.ConditionErrorNameMapper.amqp:not-implemented
  - azure-event-hubs.ConditionErrorNameMapper.amqp:precondition-failed
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-deleted
  - azure-event-hubs.ConditionErrorNameMapper.amqp:connection:framing-error
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-locked
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:errant-link
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:handle-in-use
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:unattached-handle
  - azure-event-hubs.ConditionErrorNameMapper.amqp:session:window-violation
  - azure-event-hubs.ConditionErrorNameMapper.amqp:unauthorized-access
  - azure-event-hubs.ConditionErrorNameMapper.client.sender:not-enough-link-credit
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-error
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-out-of-range
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:auth-failed
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:entity-disabled
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:message-lock-lost
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:operation-cancelled
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:precondition-failed
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:server-busy
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-cannot-be-locked
  - azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-lock-lost
  - azure-event-hubs.ConditionErrorNameMapper.amqp:resource-limit-exceeded
  langs:
  - typeScript
  type: enum
  summary: <span data-ttu-id="b4770-101">Сопоставления имен ошибки и условия.</span><span class="sxs-lookup"><span data-stu-id="b4770-101">Maps the conditions to the Error names.</span></span>
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:forced
  name: amqp:connection:forced
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-102">Когда оператор intervened, чтобы закрыть соединение, для какой-либо причине, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-102">Error is thrown when an operator intervened to close the connection for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:timeout
  name: com.microsoft:timeout
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-103">Ошибка возникает в том случае, если служба недоступна.</span><span class="sxs-lookup"><span data-stu-id="b4770-103">Error is thrown when the service is unavailable.</span></span> <span data-ttu-id="b4770-104">Следует повторить операцию.</span><span class="sxs-lookup"><span data-stu-id="b4770-104">The operation should be retried.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:redirect
  name: amqp:connection:redirect
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-105">Ошибка возникает в том случае, если контейнер больше не доступны в текущем соединении.</span><span class="sxs-lookup"><span data-stu-id="b4770-105">Error is thrown when the container is no longer available on the current connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:decode-error
  name: amqp:decode-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-106">Ошибка возникает в том случае, когда не удалось расшифровать данные.</span><span class="sxs-lookup"><span data-stu-id="b4770-106">Error is thrown when data could not be decoded.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:frame-size-too-small
  name: amqp:frame-size-too-small
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-107">Ошибка возникает в том случае, когда одноранговый узел не удается отправить кадр, поскольку наименьшее кодировку перформатива значениями действителен в настоящее время может быть слишком велик для обработки в рамке согласованный максимальный размер кадра.</span><span class="sxs-lookup"><span data-stu-id="b4770-107">Error is thrown when the peer cannot send a frame because the smallest encoding of the performative with the currently valid values would be too large to fit within a frame of the agreed maximum frame size.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:illegal-state
  name: amqp:illegal-state
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-108">Одноранговый узел об отправке кадра, который не поддерживается в текущем состоянии, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-108">Error is thrown when the peer sent a frame that is not permitted in the current state.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:internal-error
  name: amqp:internal-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-109">Ошибка возникает в том случае, когда произошла внутренняя ошибка сервера.</span><span class="sxs-lookup"><span data-stu-id="b4770-109">Error is thrown when an internal server error occured.</span></span> <span data-ttu-id="b4770-110">Нашли ошибку?</span><span class="sxs-lookup"><span data-stu-id="b4770-110">You may have found a bug?</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:invalid-field
  name: amqp:invalid-field
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-111">Ошибка возникает в том случае, когда было передано недопустимое поле в теле кадра, а не удается выполнить операцию.</span><span class="sxs-lookup"><span data-stu-id="b4770-111">Error is thrown when an invalid field was passed in a frame body, and the operation could not proceed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:detach-forced
  name: amqp:link:detach-forced
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-112">Когда оператор intervened для отсоединения для какой-либо причине, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-112">Error is thrown when an operator intervened to detach for some reason.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:message-size-exceeded
  name: amqp:link:message-size-exceeded
  children: []
  langs:
  - typeScript
  summary: '<span data-ttu-id="b4770-113">Ошибка возникает, когда это сообщение отправлено слишком велик: максимальный размер составляет 256 КБ.</span><span class="sxs-lookup"><span data-stu-id="b4770-113">Error is thrown when the message sent is too large: the maximum size is 256Kb.</span></span>'
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:redirect
  name: amqp:link:redirect
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-114">Ошибка возникает в том случае, если указанный адрес не может быть разрешено собой конечную точку, в текущем контейнере.</span><span class="sxs-lookup"><span data-stu-id="b4770-114">Error is thrown when the address provided cannot be resolved to a terminus at the current container.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:stolen
  name: amqp:link:stolen
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-115">Ошибка возникает в том случае, когда два или более экземпляров подключаются к одной секции со значениями разных эпохи.</span><span class="sxs-lookup"><span data-stu-id="b4770-115">Error is thrown when two or more instances connect to the same partition with different epoch values.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:link:transfer-limit-exceeded
  name: amqp:link:transfer-limit-exceeded
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-116">Одноранговый узел об отправке дополнительные передачу сообщений, чем разрешено в настоящее время ссылку, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-116">Error is thrown when the peer sent more message transfers than currently allowed on the link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-allowed
  name: amqp:not-allowed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-117">Ошибка возникает в том случае, когда операция выполняется, но не допускается.</span><span class="sxs-lookup"><span data-stu-id="b4770-117">Error is thrown when an operation is attempted but is not allowed.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-found
  name: amqp:not-found
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-118">Ошибка сообщения об обнаружении ошибок общие связи, относящиеся к операций обмена сообщениями.</span><span class="sxs-lookup"><span data-stu-id="b4770-118">Error for signaling general communication errors related to messaging operations.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:not-implemented
  name: amqp:not-implemented
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-119">Ошибка возникает в том случае, когда функция не реализована, но присутствует заполнитель.</span><span class="sxs-lookup"><span data-stu-id="b4770-119">Error is thrown when a feature is not implemented yet but the placeholder is present.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:precondition-failed
  name: amqp:precondition-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-120">Ошибка возникает в том случае, когда условие, которое следует будут соблюдены для выполнения операции.</span><span class="sxs-lookup"><span data-stu-id="b4770-120">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-deleted
  name: amqp:resource-deleted
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-121">При удалении объекта сервера, которыми он работает с, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-121">Error is thrown when a server entity the client is working with has been deleted.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:connection:framing-error
  name: amqp:connection:framing-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-122">Ошибка создается в том случае, если допустимые рамки заголовка не может быть сформированы из входящего потока.</span><span class="sxs-lookup"><span data-stu-id="b4770-122">Error is thrown when a valid frame header cannot be formed from the incoming byte stream.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-locked
  name: amqp:resource-locked
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-123">Ошибка возникает при попытке выполнить клиент для работы с объектом сервера, к которому она не имеет доступа, так как другой клиент работает с ним.</span><span class="sxs-lookup"><span data-stu-id="b4770-123">Error is thrown when the client attempted to work with a server entity to which it has no access because another client is working with it.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:errant-link
  name: amqp:session:errant-link
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-124">Ошибка возникает в том случае, если ввод получен ссылку, которая была отсоединена с ошибкой.</span><span class="sxs-lookup"><span data-stu-id="b4770-124">Error is thrown when input was received for a link that was detached with an error.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:handle-in-use
  name: amqp:session:handle-in-use
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-125">При получении операции присоединения, используя дескриптор, который уже используется для присоединенных ссылок, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-125">Error is thrown when an attach was received using a handle that is already in use for an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:unattached-handle
  name: amqp:session:unattached-handle
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-126">Ошибка возникает в том случае, если кадр (кроме присоединения) получен ссылается на дескриптор, который сейчас не используется, вложенные связи.</span><span class="sxs-lookup"><span data-stu-id="b4770-126">Error is thrown when a frame (other than attach) was received referencing a handle which is not currently in use of an attached link.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:session:window-violation
  name: amqp:session:window-violation
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-127">Ошибка возникает при входящих окно однорангового узла для сеанса.</span><span class="sxs-lookup"><span data-stu-id="b4770-127">Error is thrown when the peer violated incoming window for the session.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:unauthorized-access
  name: amqp:unauthorized-access
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-128">Ошибка возникает в том случае, когда указаны неверные параметры подключения и сервера отказывает в соединении.</span><span class="sxs-lookup"><span data-stu-id="b4770-128">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.client.sender:not-enough-link-credit
  name: client.sender:not-enough-link-credit
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-129">Ошибка возникает в том случае, когда отправитель клиента не имеет достаточно кредитов ссылку для отправки сообщения.</span><span class="sxs-lookup"><span data-stu-id="b4770-129">Error is thrown when the client sender does not have enough link credits to send the message.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-error
  name: com.microsoft:argument-error
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-130">Ошибка возникает в том случае, если получен неправильный аргумент.</span><span class="sxs-lookup"><span data-stu-id="b4770-130">Error is thrown when an incorrect argument was received.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:argument-out-of-range
  name: com.microsoft:argument-out-of-range
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-131">Если аргумент имеет значение, которое находится за пределами допустимой диапазона, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-131">Error is thrown when an argument has a value that is out of the admissible range.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:auth-failed
  name: com.microsoft:auth-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-132">Ошибка возникает в том случае, когда указаны неверные параметры подключения и сервера отказывает в соединении.</span><span class="sxs-lookup"><span data-stu-id="b4770-132">Error is thrown when the connection parameters are wrong and the server refused the connection.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:entity-disabled
  name: com.microsoft:entity-disabled
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-133">При попытке доступа или подключения к ним с отключенной сущностью обмена сообщениями, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-133">Error is thrown when trying to access/connect to a disabled messaging entity.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:message-lock-lost
  name: com.microsoft:message-lock-lost
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-134">Ошибка возникает в том случае, когда блокировка сообщения теряется.</span><span class="sxs-lookup"><span data-stu-id="b4770-134">Error is thrown when the lock on the message is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:operation-cancelled
  name: com.microsoft:operation-cancelled
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-135">Когда сервер отменяет операцию из-за Внутренняя ошибка, выдается ошибка.</span><span class="sxs-lookup"><span data-stu-id="b4770-135">Error is thrown when server cancels the operation due to an internal issue.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:precondition-failed
  name: com.microsoft:precondition-failed
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-136">Ошибка возникает в том случае, когда условие, которое следует будут соблюдены для выполнения операции.</span><span class="sxs-lookup"><span data-stu-id="b4770-136">Error is thrown when a condition that should have been met in order to execute an operation was not.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:server-busy
  name: com.microsoft:server-busy
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-137">Ошибка возникает в том случае, когда сервер занят.</span><span class="sxs-lookup"><span data-stu-id="b4770-137">Error is thrown when the server is busy.</span></span> <span data-ttu-id="b4770-138">Вызывающие объекты должны через некоторое время и повторите операцию.</span><span class="sxs-lookup"><span data-stu-id="b4770-138">Callers should wait a while and retry the operation.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-cannot-be-locked
  name: com.microsoft:session-cannot-be-locked
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-139">Ошибка возникает в том случае, заблокированной сеансов служебной шины Azure.</span><span class="sxs-lookup"><span data-stu-id="b4770-139">Error is thrown when the Azure ServiceBus session cannot be locked.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.com.microsoft:session-lock-lost
  name: com.microsoft:session-lock-lost
  children: []
  langs:
  - typeScript
  summary: <span data-ttu-id="b4770-140">Ошибка возникает в том случае, когда теряется блокировку сеанса служебной шины Azure.</span><span class="sxs-lookup"><span data-stu-id="b4770-140">Error is thrown when the lock on the Azure ServiceBus session is lost.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
- uid: azure-event-hubs.ConditionErrorNameMapper.amqp:resource-limit-exceeded
  name: amqp:resource-limit-exceeded
  children: []
  langs:
  - typeScript
  summary: >-
    <span data-ttu-id="b4770-141">Возникает ошибка была превышена квота концентратора событий Azure и служебной шины.</span><span class="sxs-lookup"><span data-stu-id="b4770-141">Error is thrown the the Azure EventHub/ServiceBus quota has been exceeded.</span></span>

    <span data-ttu-id="b4770-142">Периодический сброс квоты, эта операция будет ожидать до тех пор.</span><span class="sxs-lookup"><span data-stu-id="b4770-142">Quotas are reset periodically, this operation will have to wait until then.</span></span>

    <span data-ttu-id="b4770-143">Сущность обмена сообщениями достигла максимально допустимого размера.</span><span class="sxs-lookup"><span data-stu-id="b4770-143">The messaging entity has reached its maximum allowable size.</span></span>

    <span data-ttu-id="b4770-144">Это может произойти, если уже было открыто максимальное число получателей (равное 5) на группу потребителей.</span><span class="sxs-lookup"><span data-stu-id="b4770-144">This can happen if the maximum number of receivers (which is 5) has already been opened on a per-consumer group level.</span></span>
  type: field
  numericValue: 
  package: azure-event-hubs
